platform :ios, '9.0'

target 'Todoey-iOS13' do
  
  use_frameworks!

  # Pods for Todoey-iOS13
  
  pod 'RealmSwift'
  pod 'SwipeCellKit'

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
